name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - master # Specify the branch you want to trigger deployment from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (ensure it applies to the entire workflow)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.20.0" # Specify the correct Node.js version
      - name: Verify Node.js Version
        run: node --version # Ensure the correct version is applied

      # Step 3: Clear npm cache (force environment cleanup)
      - name: Clear npm cache
        run: npm cache clean --force

      # Step 4: Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest --force

      # Step 5: Verify Firebase CLI and Node.js Versions
      - name: Verify Firebase CLI and Node.js Versions
        run: |
          node --version
          firebase --version

      # Step 6: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 7: Build the project
      - name: Build Project
        run: npm run build

      # Step 8: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_WEBSITE_7912E }}
          channelId: live
          projectId: portfolio-website-7912e
